In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
ds=pd.read_csv('career_questions.csv')

In [4]:
ds.head()

,QNo,Question,Answer A,Careers A,Answer B,Careers B,Answer C,Careers C,Answer D,Careers D
0,1,What interests you the most in computing?,Building applications,"Software Engineer, Full Stack Developer",Analyzing data trends,"Data Scientist, Data Engineer",Securing networks,"Cybersecurity Analyst, System Administrator",Designing user interfaces,"UI/UX Designer, Mobile App Developer"
1,2,Which of these projects excites you the most?,A web application,"Full Stack Developer, Software Engineer",A chatbot using AI,"AI/ML Engineer, Data Scientist",A security tool,"Cybersecurity Analyst, Blockchain Developer",A 3D game,"Game Developer, Mobile App Developer"
2,3,What do you enjoy the most in a project?,Writing backend logic,"Software Engineer, Full Stack Developer",Optimizing large datasets,"Data Engineer, Database Administrator",Securing the application,"Cybersecurity Analyst, DevOps Engineer",Making it visually appealing,"UI/UX Designer, Game Developer"
3,4,How do you approach problem-solving?,Writing algorithms,"AI/ML Engineer, Software Engineer",Visualizing data,"Data Scientist, Data Engineer",Thinking like a hacker,"Cybersecurity Analyst, Blockchain Developer",Optimizing systems,"System Administrator, Cloud Engineer"
4,5,What kind of company do you want to work in?,A tech startup,"Full Stack Developer, Mobile App Developer",A finance company,"Data Scientist, Blockchain Developer",A cloud computing firm,"Cloud Engineer, DevOps Engineer",A gaming company,"Game Developer, UI/UX Designer"

In [5]:
ds.iloc[0]

QNo                                                    1
Question       What interests you the most in computing?
Answer A                           Building applications
Careers A        Software Engineer, Full Stack Developer
Answer B                           Analyzing data trends
Careers B                  Data Scientist, Data Engineer
Answer C                               Securing networks
Careers C    Cybersecurity Analyst, System Administrator
Answer D                       Designing user interfaces
Careers D           UI/UX Designer, Mobile App Developer
Name: 0, dtype: object

In [6]:
questions=[]

In [7]:
def get_careers(i):
    career_A= ds.iloc[i]['Careers A'].split(',')
    career_B=ds.iloc[i]['Careers B'].split(',')
    career_C=ds.iloc[i]['Careers C'].split(',')
    career_D=ds.iloc[i]['Careers D'].split(',')
    
    for career in career_A:
        record=[i,career,1,0,0,0]
        questions.append(record)
    for career in career_B:
        record=[i,career,0,1,0,0]
        questions.append(record)
    for career in career_C:
        record=[i,career,0,0,1,0]
        questions.append(record)
    for career in career_D:
        record=[i,career,0,0,0,1]
        questions.append(record)

In [8]:
for i in ds.index:
    get_careers(i)

In [9]:
questions

[[0, 'Software Engineer', 1, 0, 0, 0],
 [0, ' Full Stack Developer', 1, 0, 0, 0],
 [0, 'Data Scientist', 0, 1, 0, 0],
 [0, ' Data Engineer', 0, 1, 0, 0],
 [0, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [0, ' System Administrator', 0, 0, 1, 0],
 [0, 'UI/UX Designer', 0, 0, 0, 1],
 [0, ' Mobile App Developer', 0, 0, 0, 1],
 [1, 'Full Stack Developer', 1, 0, 0, 0],
 [1, ' Software Engineer', 1, 0, 0, 0],
 [1, 'AI/ML Engineer', 0, 1, 0, 0],
 [1, ' Data Scientist', 0, 1, 0, 0],
 [1, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [1, ' Blockchain Developer', 0, 0, 1, 0],
 [1, 'Game Developer', 0, 0, 0, 1],
 [1, ' Mobile App Developer', 0, 0, 0, 1],
 [2, 'Software Engineer', 1, 0, 0, 0],
 [2, ' Full Stack Developer', 1, 0, 0, 0],
 [2, 'Data Engineer', 0, 1, 0, 0],
 [2, ' Database Administrator', 0, 1, 0, 0],
 [2, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [2, ' DevOps Engineer', 0, 0, 1, 0],
 [2, 'UI/UX Designer', 0, 0, 0, 1],
 [2, ' Game Developer', 0, 0, 0, 1],
 [3, 'AI/ML Engineer', 1, 0, 0, 0],
 [3, ' Software Engineer', 1, 0, 0, 0],
 [3, 'Data Scientist', 0, 1, 0, 0],
 [3, ' Data Engineer', 0, 1, 0, 0],
 [3, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [3, ' Blockchain Developer', 0, 0, 1, 0],
 [3, 'System Administrator', 0, 0, 0, 1],
 [3, ' Cloud Engineer', 0, 0, 0, 1],
 [4, 'Full Stack Developer', 1, 0, 0, 0],
 [4, ' Mobile App Developer', 1, 0, 0, 0],
 [4, 'Data Scientist', 0, 1, 0, 0],
 [4, ' Blockchain Developer', 0, 1, 0, 0],
 [4, 'Cloud Engineer', 0, 0, 1, 0],
 [4, ' DevOps Engineer', 0, 0, 1, 0],
 [4, 'Game Developer', 0, 0, 0, 1],
 [4, ' UI/UX Designer', 0, 0, 0, 1],
 [5, 'Software Engineer', 1, 0, 0, 0],
 [5, ' AI/ML Engineer', 1, 0, 0, 0],
 [5, 'Data Engineer', 0, 1, 0, 0],
 [5, ' Data Scientist', 0, 1, 0, 0],
 [5, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [5, ' System Administrator', 0, 0, 1, 0],
 [5, 'UI/UX Designer', 0, 0, 0, 1],
 [5, ' Game Developer', 0, 0, 0, 1],
 [6, 'Full Stack Developer', 1, 0, 0, 0],
 [6, ' Cloud Engineer', 1, 0, 0, 0],
 [6, 'Data Scientist', 0, 1, 0, 0],
 [6, ' AI/ML Engineer', 0, 1, 0, 0],
 [6, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [6, ' Blockchain Developer', 0, 0, 1, 0],
 [6, 'UI/UX Designer', 0, 0, 0, 1],
 [6, ' Game Developer', 0, 0, 0, 1],
 [7, 'Software Engineer', 1, 0, 0, 0],
 [7, ' Full Stack Developer', 1, 0, 0, 0],
 [7, 'AI/ML Engineer', 0, 1, 0, 0],
 [7, ' Data Scientist', 0, 1, 0, 0],
 [7, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [7, ' Blockchain Developer', 0, 0, 1, 0],
 [7, 'UI/UX Designer', 0, 0, 0, 1],
 [7, ' Game Developer', 0, 0, 0, 1],
 [8, 'Full Stack Developer', 1, 0, 0, 0],
 [8, ' Mobile App Developer', 1, 0, 0, 0],
 [8, 'Data Scientist', 0, 1, 0, 0],
 [8, ' AI/ML Engineer', 0, 1, 0, 0],
 [8, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [8, ' System Administrator', 0, 0, 1, 0],
 [8, 'UI/UX Designer', 0, 0, 0, 1],
 [8, ' Game Developer', 0, 0, 0, 1],
 [9, 'Software Engineer', 1, 0, 0, 0],
 [9, ' DevOps Engineer', 1, 0, 0, 0],
 [9, 'AI/ML Engineer', 0, 1, 0, 0],
 [9, ' Data Scientist', 0, 1, 0, 0],
 [9, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [9, ' System Administrator', 0, 0, 1, 0],
 [9, 'UI/UX Designer', 0, 0, 0, 1],
 [9, ' Game Developer', 0, 0, 0, 1],
 [10, 'Full Stack Developer', 1, 0, 0, 0],
 [10, ' Cloud Engineer', 1, 0, 0, 0],
 [10, 'AI/ML Engineer', 0, 1, 0, 0],
 [10, ' Data Scientist', 0, 1, 0, 0],
 [10, 'Blockchain Developer', 0, 0, 1, 0],
 [10, ' Cybersecurity Analyst', 0, 0, 1, 0],
 [10, 'Game Developer', 0, 0, 0, 1],
 [10, ' UI/UX Designer', 0, 0, 0, 1],
 [11, 'Full Stack Developer', 1, 0, 0, 0],
 [11, ' Mobile App Developer', 1, 0, 0, 0],
 [11, 'AI/ML Engineer', 0, 1, 0, 0],
 [11, ' Data Scientist', 0, 1, 0, 0],
 [11, 'Cloud Engineer', 0, 0, 1, 0],
 [11, ' DevOps Engineer', 0, 0, 1, 0],
 [11, 'Game Developer', 0, 0, 0, 1],
 [11, ' UI/UX Designer', 0, 0, 0, 1],
 [12, 'Software Engineer', 1, 0, 0, 0],
 [12, ' Full Stack Developer', 1, 0, 0, 0],
 [12, 'Data Scientist', 0, 1, 0, 0],
 [12, ' Data Engineer', 0, 1, 0, 0],
 [12, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [12, ' Blockchain Developer', 0, 0, 1, 0],
 [12, 'UI/UX Designer', 0, 0, 0, 1],
 [12, ' Game Developer', 0, 0, 0, 1],
 [13, 'AI/ML Engineer', 1, 0, 0, 0],
 [13, ' Data Scientist', 1, 0, 0, 0],
 [13, 'Cloud Engineer', 0, 1, 0, 0],
 [13, ' DevOps Engineer', 0, 1, 0, 0],
 [13, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [13, ' Blockchain Developer', 0, 0, 1, 0],
 [13, 'UI/UX Designer', 0, 0, 0, 1],
 [13, ' Game Developer', 0, 0, 0, 1],
 [14, 'Software Engineer', 1, 0, 0, 0],
 [14, ' Full Stack Developer', 1, 0, 0, 0],
 [14, 'Data Engineer', 0, 1, 0, 0],
 [14, ' System Administrator', 0, 1, 0, 0],
 [14, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [14, ' Blockchain Developer', 0, 0, 1, 0],
 [14, 'UI/UX Designer', 0, 0, 0, 1],
 [14, ' Game Developer', 0, 0, 0, 1],
 [15, 'Software Engineer', 1, 0, 0, 0],
 [15, ' Full Stack Developer', 1, 0, 0, 0],
 [15, 'Data Scientist', 0, 1, 0, 0],
 [15, ' Data Engineer', 0, 1, 0, 0],
 [15, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [15, ' Blockchain Developer', 0, 0, 1, 0],
 [15, 'Game Developer', 0, 0, 0, 1],
 [15, ' UI/UX Designer', 0, 0, 0, 1],
 [16, 'Full Stack Developer', 1, 0, 0, 0],
 [16, ' Software Engineer', 1, 0, 0, 0],
 [16, 'AI/ML Engineer', 0, 1, 0, 0],
 [16, ' Data Scientist', 0, 1, 0, 0],
 [16, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [16, ' Blockchain Developer', 0, 0, 1, 0],
 [16, 'Game Developer', 0, 0, 0, 1],
 [16, ' UI/UX Designer', 0, 0, 0, 1],
 [17, 'Full Stack Developer', 1, 0, 0, 0],
 [17, ' Software Engineer', 1, 0, 0, 0],
 [17, 'AI/ML Engineer', 0, 1, 0, 0],
 [17, ' Data Scientist', 0, 1, 0, 0],
 [17, 'Blockchain Developer', 0, 0, 1, 0],
 [17, ' Cybersecurity Analyst', 0, 0, 1, 0],
 [17, 'Game Developer', 0, 0, 0, 1],
 [17, ' UI/UX Designer', 0, 0, 0, 1],
 [18, 'Software Engineer', 1, 0, 0, 0],
 [18, ' Full Stack Developer', 1, 0, 0, 0],
 [18, 'AI/ML Engineer', 0, 1, 0, 0],
 [18, ' Data Scientist', 0, 1, 0, 0],
 [18, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [18, ' System Administrator', 0, 0, 1, 0],
 [18, 'UI/UX Designer', 0, 0, 0, 1],
 [18, ' Game Developer', 0, 0, 0, 1],
 [19, 'Software Engineer', 1, 0, 0, 0],
 [19, ' Full Stack Developer', 1, 0, 0, 0],
 [19, 'Data Scientist', 0, 1, 0, 0],
 [19, ' Data Engineer', 0, 1, 0, 0],
 [19, 'Cybersecurity Analyst', 0, 0, 1, 0],
 [19, ' Blockchain Developer', 0, 0, 1, 0],
 [19, 'UI/UX Designer', 0, 0, 0, 1],
 [19, ' Game Developer', 0, 0, 0, 1]]

In [10]:
questions=pd.DataFrame(data=questions,columns=['QNo','Career','Answer A','Answer B','Answer C','Answer D'])

In [11]:
questions

     QNo                 Career  Answer A  Answer B  Answer C  Answer D
0      0      Software Engineer         1         0         0         0
1      0   Full Stack Developer         1         0         0         0
2      0         Data Scientist         0         1         0         0
3      0          Data Engineer         0         1         0         0
4      0  Cybersecurity Analyst         0         0         1         0
..   ...                    ...       ...       ...       ...       ...
155   19          Data Engineer         0         1         0         0
156   19  Cybersecurity Analyst         0         0         1         0
157   19   Blockchain Developer         0         0         1         0
158   19         UI/UX Designer         0         0         0         1
159   19         Game Developer         0         0         0         1

[160 rows x 6 columns]

In [12]:
questions.to_csv('prepared_dataset.csv')